# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 闲情偶寄
author: "Thomas Yang"
email: thomasyang00100@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  聚沙成塔
baseurl: "" # the subpath of your site, e.g. /blog
domain: blog.thomas-yang.com
url: "https://blog.thomas-yang.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username: meiyingqishi

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

disqus:
  shortname: thomasyang

show_excerpts: false

google_analytics: UA-NNNNNNNN-N

paginate: 8

lang: zh-CN

algolia:
  application_id: "1PYOYL3S5H"
  index_name: "thomasyang"
  search_only_api_key: 6e1e8b894df030a74f4230ecc5678b5d
  files_to_exclude:
    - index.html
    - about.md
